local fzf = require('fzf-lua')
vim.keymap.set('n', '<leader>fh', fzf.oldfiles)
vim.keymap.set('n', '<leader>ff', fzf.files)
vim.keymap.set('n', '<leader>rg', fzf.live_grep)
vim.keymap.set('n', '<leader>fg', fzf.git_status)
